### ISSUE TITLE
Durative actions highlighting not working

### ISSUE THREAD

**Issue by boxanm** [Pold87/myPDDL-Atom#1]
The highlighting stops working after the duration part of a durative action. If one comments this part,  the syntax highlighting is working again.

![Screenshot_2019-05-14_10-30-18](https://user-images.githubusercontent.com/47394922/57683286-a7ac3000-7633-11e9-8add-a68c4a29825e.png)

**Comment by ztangent** [comment]
The pull request I've made in #2 should fix this issue -- the problem is with how `=` predicates get parsed and highlighted.
